# Takes in code, returns (line, exception type)
# returns None if there is no error
def get_error(code):
    pass    
